namespace ZamAiMart.Client.Models;

public static class StaticData
{
    private static string FormatPrice(decimal price, PricingType pricingType, bool isFree)
    {
        if (isFree || pricingType == PricingType.Free) return "FREE";
        return pricingType switch
        {
            PricingType.Monthly  => $"Rs.{price:N0}/month",
            PricingType.Yearly   => $"Rs.{price:N0}/year",
            PricingType.OneTime  => $"Rs.{price:N0} one-time",
            PricingType.Freemium => price > 0 ? $"Free / Rs.{price:N0}/month" : "Freemium",
            _                    => price > 0 ? $"Rs.{price:N0}" : "FREE"
        };
    }

    public static List<CategoryDto> GetCategories() => new()
    {
        new() { Id=1,  Name="AI Chatbots",           Slug="ai-chatbots",           Icon="Chat",  Description="Conversational AI assistants and chatbots",           ToolCount=21 },
        new() { Id=2,  Name="AI Image Generators",   Slug="ai-image-generators",   Icon="Image", Description="AI tools for generating and editing images",          ToolCount=20 },
        new() { Id=3,  Name="AI Video Generators",   Slug="ai-video-generators",   Icon="Video", Description="AI tools for creating and editing videos",           ToolCount=17 },
        new() { Id=4,  Name="AI Coding Tools",       Slug="ai-coding-tools",       Icon="Code",  Description="AI-powered development and coding assistants",       ToolCount=15 },
        new() { Id=5,  Name="AI Writing Tools",      Slug="ai-writing-tools",      Icon="Write", Description="AI tools for writing, editing and content creation", ToolCount=17 },
        new() { Id=6,  Name="AI Voice Tools",        Slug="ai-voice-tools",        Icon="Voice", Description="AI tools for voice synthesis and audio",             ToolCount=15 },
        new() { Id=7,  Name="AI Music Generators",   Slug="ai-music-generators",   Icon="Music", Description="AI tools for creating and composing music",         ToolCount=12 },
        new() { Id=8,  Name="AI Marketing Tools",    Slug="ai-marketing-tools",    Icon="Market",Description="AI tools for marketing and advertising",            ToolCount=13 },
        new() { Id=9,  Name="AI Productivity Tools", Slug="ai-productivity-tools", Icon="Prod",  Description="AI tools to boost productivity and workflow",        ToolCount=16 },
        new() { Id=10, Name="AI Design Tools",       Slug="ai-design-tools",       Icon="Design",Description="AI tools for graphic and UI/UX design",             ToolCount=15 },
    };

    private static List<AIToolDto> CreateTools()
    {
        var list = new List<AIToolDto>
        {
            // AI CHATBOTS (CategoryId=1)
            new() { Id=1,  Name="ChatGPT",           Description="The world's most popular AI chatbot by OpenAI. Capable of writing, coding, analysis and more.",  LogoUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/512px-ChatGPT_logo.svg.png",    WebsiteUrl="https://chat.openai.com",        CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=1666, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=true,  Tags="openai,gpt,chatbot" },
            new() { Id=2,  Name="Claude",            Description="Anthropic's AI assistant known for safety and thoughtful, nuanced responses.",                    LogoUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Anthropic_logo.svg/1024px-Anthropic_logo.svg.png", WebsiteUrl="https://claude.ai",              CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=1666, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=true,  Tags="anthropic,claude,chatbot" },
            new() { Id=3,  Name="Gemini",            Description="Google's advanced AI assistant with multimodal capabilities and deep Google integration.",        LogoUrl="https://lh3.googleusercontent.com/e9tBGjB80AFLUlgCKNcG5HHBJLVdMnQnF6F3uJLSp0RRiNFMidSsRm2W5aNmvCmFb5pbbJYiinQZzHYAR0xrDZ1yXJhFUY_TZ6j8wQ=s0", WebsiteUrl="https://gemini.google.com",    CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=1666, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=true,  Tags="google,gemini,chatbot" },
            new() { Id=4,  Name="Perplexity AI",     Description="AI-powered search engine that gives cited, real-time answers with web search.",                   LogoUrl="https://upload.wikimedia.org/wikipedia/commons/1/1d/Perplexity_AI_logo.svg",                             WebsiteUrl="https://perplexity.ai",          CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=1666, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=true,  Tags="perplexity,chatbot,search" },
            new() { Id=5,  Name="Microsoft Copilot", Description="Microsoft's AI assistant powered by GPT-4, integrated across Microsoft products.",               LogoUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Microsoft_Copilot_Logo.svg/800px-Microsoft_Copilot_Logo.svg.png", WebsiteUrl="https://copilot.microsoft.com",CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=true,  Tags="microsoft,copilot,free" },
            new() { Id=6,  Name="Pi by Inflection",  Description="A personal AI for everyday conversations, designed to be supportive and curious.",               LogoUrl="https://pi.ai/favicon.ico",                                                                               WebsiteUrl="https://pi.ai",                  CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="inflection,pi,chatbot" },
            new() { Id=7,  Name="Meta AI",           Description="Meta's AI assistant available across WhatsApp, Instagram, Messenger and Facebook.",              LogoUrl="https://static.xx.fbcdn.net/rsrc.php/v3/yy/r/L_ojZTY5BwY.png",                                         WebsiteUrl="https://meta.ai",                CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="meta,ai,free" },
            new() { Id=8,  Name="Grok by xAI",      Description="Elon Musk's xAI chatbot with real-time X/Twitter data and witty personality.",                   LogoUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Grok_logo.svg/512px-Grok_logo.svg.png",      WebsiteUrl="https://grok.x.ai",              CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=999,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="xai,grok,chatbot" },
            new() { Id=9,  Name="Poe by Quora",     Description="Access multiple AI models including GPT-4, Claude, and more in one place.",                      LogoUrl="https://poe.com/favicon.ico",                                                                             WebsiteUrl="https://poe.com",                CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=1499, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="poe,quora,multi-model" },
            new() { Id=10, Name="Character.AI",      Description="Create and chat with AI characters from books, movies, celebrities and more.",                   LogoUrl="https://character.ai/favicon.ico",                                                                        WebsiteUrl="https://character.ai",           CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=999,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="character,roleplay,chatbot" },
            new() { Id=11, Name="You.com",           Description="AI-powered search and chat assistant with real-time web access.",                                LogoUrl="https://you.com/favicon.ico",                                                                             WebsiteUrl="https://you.com",                CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=1249, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="you,search,chatbot" },
            new() { Id=12, Name="Mistral Le Chat",   Description="Fast, efficient AI chat by Mistral AI with multilingual support.",                               LogoUrl="https://mistral.ai/favicon.ico",                                                                          WebsiteUrl="https://chat.mistral.ai",        CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="mistral,chat,free" },
            new() { Id=13, Name="HuggingChat",       Description="Open-source AI chatbot by Hugging Face with various model options.",                             LogoUrl="https://huggingface.co/favicon.ico",                                                                      WebsiteUrl="https://huggingface.co/chat",    CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="huggingface,open-source,free" },
            new() { Id=14, Name="Bing Chat",         Description="Microsoft Bing's AI chat with up-to-date web information powered by GPT-4.",                    LogoUrl="https://www.bing.com/favicon.ico",                                                                        WebsiteUrl="https://bing.com/chat",          CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="bing,microsoft,free" },
            new() { Id=15, Name="Replika",           Description="Your personal AI companion that listens, learns and is always here for you.",                    LogoUrl="https://replika.com/favicon.ico",                                                                         WebsiteUrl="https://replika.com",            CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=1249, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="replika,companion,emotional" },
            new() { Id=16, Name="Kuki AI",           Description="World's most human-like conversational AI chatbot platform.",                                    LogoUrl="https://www.kuki.ai/favicon.ico",                                                                         WebsiteUrl="https://www.kuki.ai",            CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="kuki,humanlike,chatbot" },
            new() { Id=17, Name="Jasper Chat",       Description="AI chat interface by Jasper for marketing teams and content creators.",                          LogoUrl="https://www.jasper.ai/favicon.ico",                                                                       WebsiteUrl="https://www.jasper.ai/chat",     CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=3249, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="jasper,marketing,chat" },
            new() { Id=18, Name="Chatsonic",         Description="AI chatbot with real-time Google data and voice capabilities.",                                  LogoUrl="https://writesonic.com/favicon.ico",                                                                      WebsiteUrl="https://writesonic.com/chat",    CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=1666, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="chatsonic,realtime,voice" },
            new() { Id=19, Name="Phind",             Description="AI search engine and coding assistant specifically designed for developers.",                     LogoUrl="https://www.phind.com/favicon.ico",                                                                       WebsiteUrl="https://www.phind.com",          CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="phind,developer,coding,free" },
            new() { Id=20, Name="DeepSeek Chat",     Description="Powerful open-source AI chatbot from DeepSeek with advanced reasoning.",                        LogoUrl="https://chat.deepseek.com/favicon.ico",                                                                   WebsiteUrl="https://chat.deepseek.com",      CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="deepseek,open-source,free" },
            new() { Id=21, Name="Cohere Chat",       Description="Enterprise AI chat platform with powerful language models for business.",                        LogoUrl="https://cohere.com/favicon.ico",                                                                          WebsiteUrl="https://cohere.com/chat",        CategoryId=1, CategoryName="AI Chatbots", CategoryIcon="Chat", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="cohere,enterprise,chat" },

            // AI IMAGE GENERATORS (CategoryId=2)
            new() { Id=22, Name="Midjourney",          Description="Industry-leading AI image generator creating stunning, artistic visuals.",         LogoUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Midjourney_Emblem.png/512px-Midjourney_Emblem.png", WebsiteUrl="https://midjourney.com",                    CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=833,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=true,  Tags="midjourney,image,art" },
            new() { Id=23, Name="DALL-E 3",            Description="OpenAI's advanced image generation model with precise prompt understanding.",      LogoUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/512px-ChatGPT_logo.svg.png",    WebsiteUrl="https://openai.com/dall-e-3",               CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=1666, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=true,  Tags="openai,dalle,image" },
            new() { Id=24, Name="Stable Diffusion",    Description="Open-source AI image generation model for creating high-quality images.",         LogoUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Stable-diffusion.svg/512px-Stable-diffusion.svg.png", WebsiteUrl="https://stability.ai",                   CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=true,  Tags="stable-diffusion,open-source,free" },
            new() { Id=25, Name="Adobe Firefly",       Description="Adobe's generative AI for images, built with commercially safe training data.",   LogoUrl="https://www.adobe.com/favicon.ico",                                                                          WebsiteUrl="https://firefly.adobe.com",                 CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=4150, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=true,  Tags="adobe,firefly,image" },
            new() { Id=26, Name="Canva AI",            Description="AI-powered design and image generation integrated into Canva's platform.",        LogoUrl="https://static.canva.com/static/images/favicon.ico",                                                         WebsiteUrl="https://canva.com",                         CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=999,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="canva,design,image" },
            new() { Id=27, Name="Leonardo AI",         Description="AI image creation platform with fine-tuned models for game assets and art.",      LogoUrl="https://leonardo.ai/favicon.ico",                                                                            WebsiteUrl="https://leonardo.ai",                       CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=999,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="leonardo,game,art,image" },
            new() { Id=28, Name="Ideogram",            Description="AI image generator that excels at creating images with accurate text rendering.", LogoUrl="https://ideogram.ai/favicon.ico",                                                                            WebsiteUrl="https://ideogram.ai",                       CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=749,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="ideogram,text,image" },
            new() { Id=29, Name="Playground AI",       Description="Free AI image creator with easy-to-use interface and multiple model support.",   LogoUrl="https://playgroundai.com/favicon.ico",                                                                       WebsiteUrl="https://playgroundai.com",                   CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="playground,image,free" },
            new() { Id=30, Name="Flux AI",             Description="State-of-the-art open image synthesis model by Black Forest Labs.",               LogoUrl="https://blackforestlabs.ai/favicon.ico",                                                                     WebsiteUrl="https://blackforestlabs.ai",                 CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="flux,image,open-source" },
            new() { Id=31, Name="Bing Image Creator",  Description="Microsoft's free AI image generator powered by DALL-E.",                          LogoUrl="https://www.bing.com/favicon.ico",                                                                           WebsiteUrl="https://www.bing.com/images/create",         CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="bing,microsoft,image,free" },
            new() { Id=32, Name="NightCafe Creator",   Description="AI art generator with multiple algorithms and community features.",                LogoUrl="https://creator.nightcafe.studio/favicon.ico",                                                               WebsiteUrl="https://creator.nightcafe.studio",           CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=749,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="nightcafe,art,community" },
            new() { Id=33, Name="DreamStudio",         Description="Official Stable Diffusion interface by Stability AI with advanced controls.",     LogoUrl="https://dreamstudio.ai/favicon.ico",                                                                         WebsiteUrl="https://dreamstudio.ai",                     CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=0,    PricingType=PricingType.Freemium, IsFree=false, IsFeatured=false, Tags="dreamstudio,stability,image" },
            new() { Id=34, Name="Artbreeder",          Description="Collaborative AI art tool for blending and creating unique visual imagery.",       LogoUrl="https://www.artbreeder.com/favicon.ico",                                                                     WebsiteUrl="https://www.artbreeder.com",                 CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=749,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="artbreeder,blend,art" },
            new() { Id=35, Name="Craiyon",             Description="Free AI image generator formerly known as DALL-E mini.",                          LogoUrl="https://www.craiyon.com/favicon.ico",                                                                        WebsiteUrl="https://www.craiyon.com",                    CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="craiyon,free,image" },
            new() { Id=36, Name="Getimg.ai",           Description="Suite of AI image tools: generate, edit, and expand images at scale.",            LogoUrl="https://getimg.ai/favicon.ico",                                                                              WebsiteUrl="https://getimg.ai",                          CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=999,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="getimg,image,edit" },
            new() { Id=37, Name="Deep Dream Generator",Description="Transform photos using Google's Deep Dream neural network.",                        LogoUrl="https://deepdreamgenerator.com/favicon.ico",                                                                 WebsiteUrl="https://deepdreamgenerator.com",             CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=499,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="deepdream,neural,photo" },
            new() { Id=38, Name="Fotor AI",            Description="AI-powered photo editor and image generator with one-click enhancements.",        LogoUrl="https://www.fotor.com/favicon.ico",                                                                          WebsiteUrl="https://www.fotor.com/ai-image-generator/", CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=666,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="fotor,photo,editor" },
            new() { Id=39, Name="Pika Labs",           Description="Advanced AI art studio for generating unique and beautiful visuals.",              LogoUrl="https://pika.art/favicon.ico",                                                                               WebsiteUrl="https://pika.art",                           CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=666,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="pika,art,image" },
            new() { Id=40, Name="Pixlr AI",            Description="Web-based AI photo editor with powerful image generation features.",               LogoUrl="https://pixlr.com/favicon.ico",                                                                              WebsiteUrl="https://pixlr.com",                          CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=499,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="pixlr,photo,editor" },
            new() { Id=41, Name="StarryAI",            Description="AI art generator with complete art ownership and fine-tuned control.",             LogoUrl="https://starryai.com/favicon.ico",                                                                           WebsiteUrl="https://starryai.com",                       CategoryId=2, CategoryName="AI Image Generators", CategoryIcon="Image", Price=999,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="starryai,art,ownership" },

            // AI VIDEO GENERATORS (CategoryId=3)
            new() { Id=42, Name="Runway ML",          Description="Professional AI video generation and editing studio with Gen-2 and Gen-3 models.", LogoUrl="https://runwayml.com/favicon.ico",             WebsiteUrl="https://runwayml.com",              CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=true,  Tags="runway,video,professional" },
            new() { Id=43, Name="Sora by OpenAI",     Description="OpenAI's text-to-video model creating realistic and imaginative scenes.",           LogoUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/512px-ChatGPT_logo.svg.png", WebsiteUrl="https://sora.com",  CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=1666, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=true,  Tags="openai,sora,video" },
            new() { Id=44, Name="Synthesia",          Description="Create AI videos with talking avatars from text in minutes.",                        LogoUrl="https://www.synthesia.io/favicon.ico",        WebsiteUrl="https://www.synthesia.io",           CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=2249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=true,  Tags="synthesia,avatar,video" },
            new() { Id=45, Name="Pika Art",           Description="AI video generation tool for creating videos from images and text prompts.",        LogoUrl="https://pika.art/favicon.ico",                WebsiteUrl="https://pika.art",                   CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=666,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="pika,video,text-to-video" },
            new() { Id=46, Name="Kling AI",           Description="Advanced AI video generation model by Kuaishou with high-quality outputs.",         LogoUrl="https://klingai.com/favicon.ico",             WebsiteUrl="https://klingai.com",                CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=999,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="kling,video,ai" },
            new() { Id=47, Name="HeyGen",             Description="Create professional AI videos with custom avatars for presentations.",               LogoUrl="https://www.heygen.com/favicon.ico",          WebsiteUrl="https://www.heygen.com",             CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=2499, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="heygen,avatar,presentation" },
            new() { Id=48, Name="Luma Dream Machine", Description="Photorealistic video generation from text and images by Luma AI.",                   LogoUrl="https://lumalabs.ai/favicon.ico",             WebsiteUrl="https://lumalabs.ai/dream-machine",  CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="luma,video,photorealistic" },
            new() { Id=49, Name="InVideo AI",         Description="AI-powered video creation platform with templates for YouTube and social media.",    LogoUrl="https://invideo.io/favicon.ico",              WebsiteUrl="https://invideo.io",                 CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=1999, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="invideo,youtube,social" },
            new() { Id=50, Name="Descript",           Description="Video and podcast editor with AI transcription and screen recording.",               LogoUrl="https://www.descript.com/favicon.ico",        WebsiteUrl="https://www.descript.com",           CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=999,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="descript,podcast,transcription" },
            new() { Id=51, Name="Captions AI",        Description="AI video creation tool with auto-captions, avatars and teleprompter.",               LogoUrl="https://www.captions.ai/favicon.ico",         WebsiteUrl="https://www.captions.ai",            CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=999,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="captions,subtitles,video" },
            new() { Id=52, Name="Genmo",              Description="Creative AI for animated videos, stories and interactive content.",                   LogoUrl="https://www.genmo.ai/favicon.ico",            WebsiteUrl="https://www.genmo.ai",               CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=833,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="genmo,animated,stories" },
            new() { Id=53, Name="Veed.io",            Description="Online video editor with AI tools for subtitles, translation, and enhancement.",     LogoUrl="https://www.veed.io/favicon.ico",             WebsiteUrl="https://www.veed.io",                CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="veed,subtitle,editor" },
            new() { Id=54, Name="Pictory",            Description="Turn long-form content into short, shareable videos with AI.",                       LogoUrl="https://pictory.ai/favicon.ico",              WebsiteUrl="https://pictory.ai",                 CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=1999, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="pictory,short-video,content" },
            new() { Id=55, Name="Fliki AI",           Description="Text to video and speech with 2000+ realistic voices and stock media.",               LogoUrl="https://fliki.ai/favicon.ico",                WebsiteUrl="https://fliki.ai",                   CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=666,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="fliki,text-to-video,voice" },
            new() { Id=56, Name="Steve AI",           Description="AI text-to-video platform using human artists and AI for professional quality.",     LogoUrl="https://www.steve.ai/favicon.ico",            WebsiteUrl="https://www.steve.ai",               CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=1666, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="steve,text-to-video,animation" },
            new() { Id=57, Name="Kapwing",            Description="Collaborative AI video editor for teams with smart trimming and subtitles.",          LogoUrl="https://www.kapwing.com/favicon.ico",         WebsiteUrl="https://www.kapwing.com",            CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="kapwing,collaborative,editing" },
            new() { Id=58, Name="Opus Clip",          Description="AI video repurposing tool that turns long videos into viral short clips.",             LogoUrl="https://www.opus.pro/favicon.ico",            WebsiteUrl="https://www.opus.pro",               CategoryId=3, CategoryName="AI Video Generators", CategoryIcon="Video", Price=999,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="opus,clip,short,viral" },

            // AI CODING TOOLS (CategoryId=4)
            new() { Id=59, Name="GitHub Copilot",        Description="AI pair programmer by GitHub that suggests code in real-time as you type.",             LogoUrl="https://github.com/favicon.ico",           WebsiteUrl="https://github.com/features/copilot",   CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=833,   PricingType=PricingType.Monthly, IsFree=false, IsFeatured=true,  Tags="github,copilot,code" },
            new() { Id=60, Name="Cursor",                Description="AI-first code editor built on VSCode with powerful AI coding assistance.",             LogoUrl="https://cursor.com/favicon.ico",           WebsiteUrl="https://cursor.com",                     CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=1666,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=true,  Tags="cursor,vscode,ai,editor" },
            new() { Id=61, Name="Tabnine",               Description="AI code completion tool supporting 30+ languages and all major IDEs.",                 LogoUrl="https://www.tabnine.com/favicon.ico",      WebsiteUrl="https://www.tabnine.com",                CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=999,   PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="tabnine,autocomplete,ide" },
            new() { Id=62, Name="Replit AI",             Description="AI coding assistant on Replit cloud IDE for building and deploying apps.",             LogoUrl="https://replit.com/favicon.ico",           WebsiteUrl="https://replit.com",                     CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=499,   PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="replit,cloud,ide" },
            new() { Id=63, Name="Amazon CodeWhisperer",  Description="AI code generator by Amazon trained on billions of lines of code.",                    LogoUrl="https://aws.amazon.com/favicon.ico",       WebsiteUrl="https://aws.amazon.com/codewhisperer/", CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=0,     PricingType=PricingType.Free,    IsFree=true,  IsFeatured=false, Tags="amazon,aws,free" },
            new() { Id=64, Name="Codeium",               Description="Free AI coding toolkit for developers with 70+ language support.",                      LogoUrl="https://codeium.com/favicon.ico",          WebsiteUrl="https://codeium.com",                    CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=0,     PricingType=PricingType.Free,    IsFree=true,  IsFeatured=false, Tags="codeium,free,coding" },
            new() { Id=65, Name="Windsurf",              Description="Agentic AI IDE by Codeium that combines AI code assistance with deep context.",         LogoUrl="https://codeium.com/favicon.ico",          WebsiteUrl="https://codeium.com/windsurf",           CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=1249,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="windsurf,agentic,ide" },
            new() { Id=66, Name="Bolt.new",              Description="AI web development tool for building full-stack apps in the browser.",                  LogoUrl="https://bolt.new/favicon.ico",             WebsiteUrl="https://bolt.new",                       CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=1666,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="bolt,web,fullstack" },
            new() { Id=67, Name="v0 by Vercel",          Description="AI UI generation tool by Vercel for building React components with prompts.",           LogoUrl="https://v0.dev/favicon.ico",               WebsiteUrl="https://v0.dev",                         CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=1666,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="v0,vercel,react,ui" },
            new() { Id=68, Name="Sourcegraph Cody",      Description="AI coding assistant that understands your entire codebase for smarter suggestions.",   LogoUrl="https://sourcegraph.com/favicon.ico",      WebsiteUrl="https://sourcegraph.com/cody",           CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=0,     PricingType=PricingType.Free,    IsFree=true,  IsFeatured=false, Tags="sourcegraph,cody,free" },
            new() { Id=69, Name="Devin AI",              Description="World's first fully autonomous AI software engineer by Cognition Labs.",                LogoUrl="https://cognition.ai/favicon.ico",         WebsiteUrl="https://cognition.ai",                   CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=41500, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="devin,autonomous,swe" },
            new() { Id=70, Name="CodeRabbit",            Description="AI code review tool that gives contextual code suggestions and reviews PRs.",           LogoUrl="https://coderabbit.ai/favicon.ico",        WebsiteUrl="https://coderabbit.ai",                  CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=999,   PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="coderabbit,review,pr" },
            new() { Id=71, Name="Aider",                 Description="Open-source AI pair programming tool in your terminal for code editing.",               LogoUrl="https://aider.chat/favicon.ico",           WebsiteUrl="https://aider.chat",                     CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=0,     PricingType=PricingType.Free,    IsFree=true,  IsFeatured=false, Tags="aider,terminal,open-source" },
            new() { Id=72, Name="Pieces for Developers", Description="AI-powered developer tool for saving, enriching, and searching code snippets.",        LogoUrl="https://pieces.app/favicon.ico",           WebsiteUrl="https://pieces.app",                     CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=0,     PricingType=PricingType.Free,    IsFree=true,  IsFeatured=false, Tags="pieces,snippets,developer" },
            new() { Id=73, Name="Continue.dev",          Description="Open-source AI code assistant for VS Code and JetBrains IDEs.",                        LogoUrl="https://continue.dev/favicon.ico",         WebsiteUrl="https://continue.dev",                   CategoryId=4, CategoryName="AI Coding Tools", CategoryIcon="Code", Price=0,     PricingType=PricingType.Free,    IsFree=true,  IsFeatured=false, Tags="continue,open-source,vscode" },

            // AI WRITING TOOLS (CategoryId=5)
            new() { Id=74, Name="Jasper AI",         Description="Enterprise AI writing assistant for marketing teams, blogs, and ads.",              LogoUrl="https://www.jasper.ai/favicon.ico",       WebsiteUrl="https://www.jasper.ai",             CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=3249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=true,  Tags="jasper,marketing,writing" },
            new() { Id=75, Name="Copy.ai",           Description="AI copywriting tool for sales copy, blog posts, and social media content.",         LogoUrl="https://www.copy.ai/favicon.ico",         WebsiteUrl="https://www.copy.ai",               CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=2916, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="copyai,sales,blog" },
            new() { Id=76, Name="Writesonic",        Description="AI writing platform for creating blog posts, ads, landing pages and more.",         LogoUrl="https://writesonic.com/favicon.ico",       WebsiteUrl="https://writesonic.com",            CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="writesonic,blog,ads" },
            new() { Id=77, Name="Rytr",              Description="Affordable AI writing assistant for blogs, emails and more in 40 languages.",        LogoUrl="https://rytr.me/favicon.ico",             WebsiteUrl="https://rytr.me",                   CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=749,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="rytr,affordable,email" },
            new() { Id=78, Name="Grammarly",         Description="AI writing assistant for grammar, style, tone, and clarity improvements.",          LogoUrl="https://www.grammarly.com/favicon.ico",   WebsiteUrl="https://www.grammarly.com",         CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=999,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=true,  Tags="grammarly,grammar,style" },
            new() { Id=79, Name="Notion AI",         Description="AI writing assistant built into Notion for drafting, editing, and summarizing.",    LogoUrl="https://www.notion.so/favicon.ico",       WebsiteUrl="https://www.notion.so/product/ai",  CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=666,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="notion,writing,summary" },
            new() { Id=80, Name="Hemingway Editor",  Description="Writing app that highlights complex sentences and suggests simplifications.",        LogoUrl="https://hemingwayapp.com/favicon.ico",    WebsiteUrl="https://hemingwayapp.com",          CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=0,    PricingType=PricingType.Free,    IsFree=true,  IsFeatured=false, Tags="hemingway,editor,clarity" },
            new() { Id=81, Name="Sudowrite",         Description="AI writing partner specifically designed for fiction writers and novelists.",        LogoUrl="https://www.sudowrite.com/favicon.ico",   WebsiteUrl="https://www.sudowrite.com",          CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=833,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="sudowrite,fiction,novel" },
            new() { Id=82, Name="Wordtune",          Description="AI writing companion that helps rewrite, paraphrase, and improve sentences.",       LogoUrl="https://www.wordtune.com/favicon.ico",    WebsiteUrl="https://www.wordtune.com",          CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=666,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="wordtune,paraphrase,rewrite" },
            new() { Id=83, Name="Quillbot",          Description="AI-powered paraphrasing, summarizing, and grammar-checking writing tool.",          LogoUrl="https://quillbot.com/favicon.ico",        WebsiteUrl="https://quillbot.com",              CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=666,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="quillbot,paraphrase,grammar" },
            new() { Id=84, Name="ContentBot",        Description="AI content writer for blog posts, ads, and long-form content creation.",            LogoUrl="https://contentbot.ai/favicon.ico",       WebsiteUrl="https://contentbot.ai",             CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="contentbot,blog,longform" },
            new() { Id=85, Name="Hypotenuse AI",     Description="AI content generation platform for ecommerce product descriptions and blogs.",      LogoUrl="https://www.hypotenuse.ai/favicon.ico",   WebsiteUrl="https://www.hypotenuse.ai",         CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=2082, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="hypotenuse,ecommerce,product" },
            new() { Id=86, Name="Anyword",           Description="AI copywriting platform with predictive performance scores for marketing copy.",    LogoUrl="https://anyword.com/favicon.ico",         WebsiteUrl="https://anyword.com",               CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=3249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="anyword,copywriting,marketing" },
            new() { Id=87, Name="Surfer SEO",        Description="AI writing tool that helps create SEO-optimized content to rank higher.",           LogoUrl="https://surferseo.com/favicon.ico",       WebsiteUrl="https://surferseo.com",             CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=6250, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="surfer,seo,content" },
            new() { Id=88, Name="Frase",             Description="AI content tool that researches, writes, and optimizes SEO content.",               LogoUrl="https://www.frase.io/favicon.ico",        WebsiteUrl="https://www.frase.io",              CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="frase,seo,research" },
            new() { Id=89, Name="Longshot AI",       Description="Fact-grounded AI writing tool for creating accurate long-form content.",            LogoUrl="https://www.longshot.ai/favicon.ico",     WebsiteUrl="https://www.longshot.ai",           CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=1499, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="longshot,factual,longform" },
            new() { Id=90, Name="ProWritingAid",     Description="AI writing assistant for deeper style, grammar, and readability analysis.",         LogoUrl="https://prowritingaid.com/favicon.ico",   WebsiteUrl="https://prowritingaid.com",         CategoryId=5, CategoryName="AI Writing Tools", CategoryIcon="Write", Price=666,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="prowritingaid,style,grammar" },

            // AI VOICE TOOLS (CategoryId=6)
            new() { Id=91,  Name="ElevenLabs",       Description="State-of-the-art AI voice synthesis and cloning with ultra-realistic voices.",        LogoUrl="https://elevenlabs.io/favicon.ico",        WebsiteUrl="https://elevenlabs.io",            CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=999,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=true,  Tags="elevenlabs,tts,voice-clone" },
            new() { Id=92,  Name="Murf AI",          Description="AI voice generator with 120+ natural voices for voiceovers and presentations.",       LogoUrl="https://murf.ai/favicon.ico",              WebsiteUrl="https://murf.ai",                  CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=1666, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=true,  Tags="murf,voiceover,presentation" },
            new() { Id=93,  Name="Descript",         Description="AI-powered audio/video editor with overdub voice cloning technology.",                LogoUrl="https://www.descript.com/favicon.ico",     WebsiteUrl="https://www.descript.com",         CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=999,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="descript,overdub,voice-clone" },
            new() { Id=94,  Name="Resemble AI",      Description="AI voice cloning and speech synthesis platform for realistic audio creation.",         LogoUrl="https://www.resemble.ai/favicon.ico",      WebsiteUrl="https://www.resemble.ai",          CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=415,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="resemble,voice-clone,synthesis" },
            new() { Id=95,  Name="Speechify",        Description="AI text-to-speech tool that reads documents, articles and PDFs aloud.",               LogoUrl="https://speechify.com/favicon.ico",        WebsiteUrl="https://speechify.com",            CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=999,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="speechify,tts,reading" },
            new() { Id=96,  Name="Replica Studios",  Description="AI voice studio for game developers and content creators with 40+ voices.",           LogoUrl="https://replicastudios.com/favicon.ico",   WebsiteUrl="https://replicastudios.com",       CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="replica,game,voice" },
            new() { Id=97,  Name="Play.ht",          Description="AI text-to-speech with voice cloning and 600+ voices in 100+ languages.",             LogoUrl="https://play.ht/favicon.ico",              WebsiteUrl="https://play.ht",                  CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=2499, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="playht,tts,multilingual" },
            new() { Id=98,  Name="Otter.ai",         Description="AI meeting assistant that records, transcribes, and summarizes conversations.",        LogoUrl="https://otter.ai/favicon.ico",             WebsiteUrl="https://otter.ai",                 CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=833,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="otter,transcription,meeting" },
            new() { Id=99,  Name="Whisper by OpenAI",Description="Open-source speech recognition model with near-human transcription accuracy.",        LogoUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/512px-ChatGPT_logo.svg.png", WebsiteUrl="https://openai.com/research/whisper", CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=0, PricingType=PricingType.Free, IsFree=true, IsFeatured=false, Tags="whisper,openai,transcription" },
            new() { Id=100, Name="Lovo AI",          Description="AI voice generator and text-to-speech platform with 500+ voices.",                    LogoUrl="https://lovo.ai/favicon.ico",              WebsiteUrl="https://lovo.ai",                  CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="lovo,tts,voiceover" },
            new() { Id=101, Name="Krisp",            Description="AI noise cancellation app for crystal-clear calls in any environment.",               LogoUrl="https://krisp.ai/favicon.ico",             WebsiteUrl="https://krisp.ai",                 CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=833,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="krisp,noise-cancel,calls" },
            new() { Id=102, Name="Fireflies AI",     Description="AI meeting note-taker with transcription, search, and collaboration.",                LogoUrl="https://fireflies.ai/favicon.ico",         WebsiteUrl="https://fireflies.ai",             CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=833,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="fireflies,meeting,notes" },
            new() { Id=103, Name="Podcastle",        Description="AI-powered podcast creation and recording platform with noise reduction.",             LogoUrl="https://podcastle.ai/favicon.ico",         WebsiteUrl="https://podcastle.ai",             CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=999,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="podcastle,podcast,recording" },
            new() { Id=104, Name="Adobe Podcast",    Description="AI-powered audio recording and enhancement by Adobe for podcasters.",                  LogoUrl="https://podcast.adobe.com/favicon.ico",    WebsiteUrl="https://podcast.adobe.com",        CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=0,    PricingType=PricingType.Free,    IsFree=true,  IsFeatured=false, Tags="adobe,podcast,enhance" },
            new() { Id=105, Name="Voicemod",         Description="Real-time AI voice changer with custom soundboards for gaming and streaming.",         LogoUrl="https://www.voicemod.net/favicon.ico",     WebsiteUrl="https://www.voicemod.net",         CategoryId=6, CategoryName="AI Voice Tools", CategoryIcon="Voice", Price=833,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="voicemod,gaming,streaming" },

            // AI MUSIC GENERATORS (CategoryId=7)
            new() { Id=106, Name="Suno AI",     Description="Create complete songs with vocals from simple text prompts in seconds.",                   LogoUrl="https://suno.com/favicon.ico",           WebsiteUrl="https://suno.com",          CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=833,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=true,  Tags="suno,music,vocals" },
            new() { Id=107, Name="Udio",        Description="AI music generation platform creating radio-quality songs from descriptions.",              LogoUrl="https://www.udio.com/favicon.ico",       WebsiteUrl="https://www.udio.com",      CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=833,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=true,  Tags="udio,music,radio" },
            new() { Id=108, Name="Mubert",      Description="AI music generation API and app for royalty-free background music.",                        LogoUrl="https://mubert.com/favicon.ico",         WebsiteUrl="https://mubert.com",        CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="mubert,royalty-free,api" },
            new() { Id=109, Name="AIVA",        Description="AI music composer for emotional and cinematic soundtracks and backgrounds.",                 LogoUrl="https://www.aiva.ai/favicon.ico",        WebsiteUrl="https://www.aiva.ai",       CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=1999, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="aiva,composer,cinematic" },
            new() { Id=110, Name="Soundraw",    Description="AI music generator for creating royalty-free music with style control.",                    LogoUrl="https://soundraw.io/favicon.ico",        WebsiteUrl="https://soundraw.io",       CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=1666, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="soundraw,royalty-free,style" },
            new() { Id=111, Name="Beatoven.ai", Description="AI music creation tool for creating mood-specific background music.",                       LogoUrl="https://www.beatoven.ai/favicon.ico",    WebsiteUrl="https://www.beatoven.ai",   CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=833,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="beatoven,mood,background" },
            new() { Id=112, Name="Loudly",      Description="AI music generation platform for creators with genre and mood selection.",                   LogoUrl="https://www.loudly.com/favicon.ico",     WebsiteUrl="https://www.loudly.com",    CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=999,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="loudly,genre,mood" },
            new() { Id=113, Name="Boomy",       Description="Create original songs in seconds with AI and share them on streaming platforms.",            LogoUrl="https://boomy.com/favicon.ico",          WebsiteUrl="https://boomy.com",         CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=0,    PricingType=PricingType.Free,    IsFree=true,  IsFeatured=false, Tags="boomy,songs,streaming,free" },
            new() { Id=114, Name="Amper Music", Description="AI music composition software for creating soundtracks and background music.",              LogoUrl="https://www.ampermusic.com/favicon.ico",  WebsiteUrl="https://www.ampermusic.com",CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="amper,composition,soundtrack" },
            new() { Id=115, Name="Ecrett Music",Description="Easy AI music creator for video creators with scene-based music generation.",               LogoUrl="https://ecrettmusic.com/favicon.ico",     WebsiteUrl="https://ecrettmusic.com",   CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=833,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="ecrett,video,scene" },
            new() { Id=116, Name="Musicfy",     Description="AI song creator that transforms text and humming into full music tracks.",                   LogoUrl="https://musicfy.lol/favicon.ico",         WebsiteUrl="https://musicfy.lol",       CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=749,  PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="musicfy,humming,text-to-music" },
            new() { Id=117, Name="Soundful",    Description="AI-powered music generation platform creating unique tracks for every need.",                LogoUrl="https://soundful.com/favicon.ico",        WebsiteUrl="https://soundful.com",      CategoryId=7, CategoryName="AI Music Generators", CategoryIcon="Music", Price=1249, PricingType=PricingType.Monthly, IsFree=false, IsFeatured=false, Tags="soundful,unique,tracks" },

            // AI MARKETING TOOLS (CategoryId=8)
            new() { Id=118, Name="HubSpot AI",      Description="AI-powered CRM and marketing platform with content generation and analytics.",     LogoUrl="https://www.hubspot.com/favicon.ico",    WebsiteUrl="https://www.hubspot.com/artificial-intelligence", CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=3737, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=true,  Tags="hubspot,crm,marketing" },
            new() { Id=119, Name="Semrush AI",       Description="AI-enhanced SEO and digital marketing platform for competitive research.",         LogoUrl="https://www.semrush.com/favicon.ico",    WebsiteUrl="https://www.semrush.com",                          CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=9490, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="semrush,seo,digital" },
            new() { Id=120, Name="Mailchimp AI",     Description="Email marketing platform with AI-powered content suggestions and audience insights.",LogoUrl="https://mailchimp.com/favicon.ico",      WebsiteUrl="https://mailchimp.com",                            CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=833,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="mailchimp,email,campaign" },
            new() { Id=121, Name="AdCreative.ai",    Description="AI-powered advertising creative generation for Facebook, Google and more.",        LogoUrl="https://www.adcreative.ai/favicon.ico",  WebsiteUrl="https://www.adcreative.ai",                        CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=2082, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="adcreative,facebook,google" },
            new() { Id=122, Name="Pencil AI",        Description="AI ad creative platform that generates winning ad creatives at scale.",            LogoUrl="https://www.trypencil.com/favicon.ico",  WebsiteUrl="https://www.trypencil.com",                        CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=6650, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="pencil,ads,creative" },
            new() { Id=123, Name="Brandwatch",       Description="AI-powered consumer intelligence and social media analytics platform.",            LogoUrl="https://www.brandwatch.com/favicon.ico", WebsiteUrl="https://www.brandwatch.com",                       CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=0,    PricingType=PricingType.Freemium, IsFree=false, IsFeatured=false, Tags="brandwatch,social,analytics" },
            new() { Id=124, Name="Sprout Social AI", Description="AI-enhanced social media management with engagement and analytics tools.",         LogoUrl="https://sproutsocial.com/favicon.ico",   WebsiteUrl="https://sproutsocial.com",                         CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=1742, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="sprout,social,management" },
            new() { Id=125, Name="Smartly.io",       Description="AI-powered social advertising automation and creative optimization platform.",     LogoUrl="https://www.smartly.io/favicon.ico",     WebsiteUrl="https://www.smartly.io",                           CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=0,    PricingType=PricingType.Freemium, IsFree=false, IsFeatured=false, Tags="smartly,advertising,automation" },
            new() { Id=126, Name="Phrasee",          Description="AI language optimization for marketing copy across email, social and more.",       LogoUrl="https://phrasee.co/favicon.ico",         WebsiteUrl="https://phrasee.co",                               CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=0,    PricingType=PricingType.Freemium, IsFree=false, IsFeatured=false, Tags="phrasee,language,optimization" },
            new() { Id=127, Name="Persado",          Description="AI-generated language for marketing that motivates customers to act.",             LogoUrl="https://www.persado.com/favicon.ico",    WebsiteUrl="https://www.persado.com",                          CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=0,    PricingType=PricingType.Freemium, IsFree=false, IsFeatured=false, Tags="persado,motivation,enterprise" },
            new() { Id=128, Name="Albert AI",        Description="Autonomous digital marketing AI that self-optimizes campaigns at scale.",          LogoUrl="https://albert.ai/favicon.ico",          WebsiteUrl="https://albert.ai",                                CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=0,    PricingType=PricingType.Freemium, IsFree=false, IsFeatured=false, Tags="albert,autonomous,campaign" },
            new() { Id=129, Name="Postwise",         Description="AI Twitter/X growth tool for writing and scheduling viral threads.",              LogoUrl="https://postwise.ai/favicon.ico",        WebsiteUrl="https://postwise.ai",                              CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=2499, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="postwise,twitter,threads" },
            new() { Id=130, Name="Ocoya",            Description="AI social media marketing tool for content creation and scheduling.",             LogoUrl="https://www.ocoya.com/favicon.ico",      WebsiteUrl="https://www.ocoya.com",                            CategoryId=8, CategoryName="AI Marketing Tools", CategoryIcon="Market", Price=1999, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="ocoya,social,schedule" },

            // AI PRODUCTIVITY TOOLS (CategoryId=9)
            new() { Id=131, Name="Notion AI",         Description="AI assistant built into Notion for notes, docs, and project management.",                 LogoUrl="https://www.notion.so/favicon.ico",      WebsiteUrl="https://www.notion.so",            CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=666,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=true,  Tags="notion,notes,projects" },
            new() { Id=132, Name="Otter.ai",          Description="AI meeting assistant for real-time transcription and automated meeting notes.",            LogoUrl="https://otter.ai/favicon.ico",           WebsiteUrl="https://otter.ai",                 CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=833,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="otter,meeting,transcription" },
            new() { Id=133, Name="Motion AI",         Description="AI calendar and task manager that automatically prioritizes your schedule.",               LogoUrl="https://www.usemotion.com/favicon.ico",  WebsiteUrl="https://www.usemotion.com",        CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=1499, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="motion,calendar,schedule" },
            new() { Id=134, Name="Reclaim AI",        Description="Smart calendar AI that finds the best time for tasks and habits automatically.",           LogoUrl="https://reclaim.ai/favicon.ico",         WebsiteUrl="https://reclaim.ai",               CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=999,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="reclaim,calendar,habits" },
            new() { Id=135, Name="Mem AI",            Description="AI-powered note-taking that automatically organizes and connects your notes.",             LogoUrl="https://mem.ai/favicon.ico",             WebsiteUrl="https://mem.ai",                   CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=1249, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="mem,notes,organize" },
            new() { Id=136, Name="Taskade AI",        Description="All-in-one AI workspace for tasks, projects, and team collaboration.",                     LogoUrl="https://www.taskade.com/favicon.ico",    WebsiteUrl="https://www.taskade.com",          CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=666,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="taskade,tasks,collaboration" },
            new() { Id=137, Name="Magical",           Description="AI text expander and autofill tool for repetitive typing and form filling.",               LogoUrl="https://www.getmagical.com/favicon.ico", WebsiteUrl="https://www.getmagical.com",       CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="magical,text-expander,autofill" },
            new() { Id=138, Name="Glean AI",          Description="Enterprise AI search across all your work apps and documents.",                            LogoUrl="https://www.glean.com/favicon.ico",      WebsiteUrl="https://www.glean.com",            CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=0,    PricingType=PricingType.Freemium, IsFree=false, IsFeatured=false, Tags="glean,enterprise,search" },
            new() { Id=139, Name="Superhuman AI",     Description="AI-powered email client for executives and teams to manage inbox faster.",                 LogoUrl="https://superhuman.com/favicon.ico",     WebsiteUrl="https://superhuman.com",           CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=2499, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="superhuman,email,inbox" },
            new() { Id=140, Name="Raycast AI",        Description="Mac productivity tool with AI commands for quick actions and automation.",                 LogoUrl="https://www.raycast.com/favicon.ico",    WebsiteUrl="https://www.raycast.com",          CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=833,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="raycast,mac,launcher" },
            new() { Id=141, Name="Cron AI",           Description="AI calendar app with smart scheduling and meeting management features.",                   LogoUrl="https://cron.com/favicon.ico",           WebsiteUrl="https://cron.com",                 CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="cron,calendar,meeting" },
            new() { Id=142, Name="Zapier AI",         Description="AI-powered automation platform connecting 6000+ apps with smart workflows.",               LogoUrl="https://zapier.com/favicon.ico",         WebsiteUrl="https://zapier.com",               CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=1666, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="zapier,automation,workflow" },
            new() { Id=143, Name="Make (Integromat)", Description="Visual AI automation platform for building complex multi-step workflows.",                 LogoUrl="https://www.make.com/favicon.ico",       WebsiteUrl="https://www.make.com",             CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=749,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="make,automation,visual" },
            new() { Id=144, Name="Bardeen AI",        Description="AI automation browser extension for no-code workflows and web scraping.",                  LogoUrl="https://www.bardeen.ai/favicon.ico",     WebsiteUrl="https://www.bardeen.ai",           CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=999,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="bardeen,browser,no-code" },
            new() { Id=145, Name="Timeular",          Description="AI time tracking tool with physical and digital tracking for productivity.",                LogoUrl="https://timeular.com/favicon.ico",       WebsiteUrl="https://timeular.com",             CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=833,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="timeular,time-tracking,productivity" },
            new() { Id=146, Name="Skim AI",           Description="AI document summarizer for quickly reading research papers and reports.",                  LogoUrl="https://skim.ai/favicon.ico",            WebsiteUrl="https://skim.ai",                  CategoryId=9, CategoryName="AI Productivity Tools", CategoryIcon="Prod", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="skim,summarize,papers" },

            // AI DESIGN TOOLS (CategoryId=10)
            new() { Id=147, Name="Figma AI",              Description="AI-powered features in Figma for auto-layout, prototyping, and design suggestions.",     LogoUrl="https://www.figma.com/favicon.ico",             WebsiteUrl="https://www.figma.com",                   CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=1499, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=true,  Tags="figma,design,prototype" },
            new() { Id=148, Name="Canva AI Magic Studio", Description="AI design tools in Canva including Magic Edit, Magic Design and more.",                   LogoUrl="https://static.canva.com/static/images/favicon.ico", WebsiteUrl="https://www.canva.com/magic-studio/", CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=999,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=true,  Tags="canva,magic,design" },
            new() { Id=149, Name="Uizard",               Description="AI design tool that turns sketches and prompts into UI wireframes and mockups.",           LogoUrl="https://uizard.io/favicon.ico",                 WebsiteUrl="https://uizard.io",                       CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=1249, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="uizard,wireframe,mockup" },
            new() { Id=150, Name="Khroma",               Description="AI color tool that learns your preferences and generates beautiful palettes.",             LogoUrl="https://khroma.co/favicon.ico",                 WebsiteUrl="https://khroma.co",                       CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="khroma,color,palette,free" },
            new() { Id=151, Name="Looka",                Description="AI logo maker and brand identity tool for businesses and entrepreneurs.",                  LogoUrl="https://looka.com/favicon.ico",                 WebsiteUrl="https://looka.com",                       CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=833,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="looka,logo,brand" },
            new() { Id=152, Name="Brandmark",            Description="AI logo design tool that creates professional logos and brand kits instantly.",            LogoUrl="https://brandmark.io/favicon.ico",              WebsiteUrl="https://brandmark.io",                    CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=0,    PricingType=PricingType.OneTime,  IsFree=false, IsFeatured=false, Tags="brandmark,logo,brand-kit" },
            new() { Id=153, Name="Remove.bg",            Description="AI background removal tool that instantly removes backgrounds from photos.",               LogoUrl="https://www.remove.bg/favicon.ico",             WebsiteUrl="https://www.remove.bg",                   CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=999,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="removebg,background,photo" },
            new() { Id=154, Name="Cleanup.pictures",     Description="AI-powered object removal tool for photos with one-click deletion.",                       LogoUrl="https://cleanup.pictures/favicon.ico",          WebsiteUrl="https://cleanup.pictures",                CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=999,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="cleanup,object-remove,photo" },
            new() { Id=155, Name="Visily AI",            Description="AI-powered UI design tool for turning screenshots into editable designs.",                 LogoUrl="https://www.visily.ai/favicon.ico",             WebsiteUrl="https://www.visily.ai",                   CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=1249, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="visily,ui,screenshot" },
            new() { Id=156, Name="Framer AI",            Description="AI website builder that creates entire websites from text descriptions.",                  LogoUrl="https://www.framer.com/favicon.ico",            WebsiteUrl="https://www.framer.com",                  CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=1249, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="framer,website,builder" },
            new() { Id=157, Name="Galileo AI",           Description="AI UI design generation from text prompts for rapid product prototyping.",                 LogoUrl="https://www.usegalileo.ai/favicon.ico",         WebsiteUrl="https://www.usegalileo.ai",               CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="galileo,ui,prototyping" },
            new() { Id=158, Name="Fontjoy",              Description="AI font pairing tool that finds perfect font combinations for your designs.",              LogoUrl="https://fontjoy.com/favicon.ico",               WebsiteUrl="https://fontjoy.com",                     CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=0,    PricingType=PricingType.Free,     IsFree=true,  IsFeatured=false, Tags="fontjoy,font,typography,free" },
            new() { Id=159, Name="Magician for Figma",   Description="AI design plugin for Figma with copywriting, icon generation, and more.",                 LogoUrl="https://magician.design/favicon.ico",           WebsiteUrl="https://magician.design",                 CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=499,  PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="magician,figma,plugin" },
            new() { Id=160, Name="Wix ADI",              Description="AI-powered website builder that creates personalized websites instantly.",                 LogoUrl="https://www.wix.com/favicon.ico",               WebsiteUrl="https://www.wix.com",                     CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=1150, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="wix,website,builder" },
            new() { Id=161, Name="10Web AI",             Description="AI website builder powered by WordPress with automated site generation.",                  LogoUrl="https://10web.io/favicon.ico",                  WebsiteUrl="https://10web.io",                        CategoryId=10, CategoryName="AI Design Tools", CategoryIcon="Design", Price=1249, PricingType=PricingType.Monthly,  IsFree=false, IsFeatured=false, Tags="10web,wordpress,website" },
        };

        foreach (var t in list)
            t.FormattedPrice = FormatPrice(t.Price, t.PricingType, t.IsFree);

        return list;
    }

    private static readonly List<AIToolDto> _tools = CreateTools();

    public static List<AIToolDto> GetFeaturedTools() => _tools.Where(t => t.IsFeatured).ToList();
    public static List<AIToolDto> GetLatestTools(int count = 12) => _tools.Take(count).ToList();
    public static List<AIToolDto> GetToolsByCategory(int categoryId) => _tools.Where(t => t.CategoryId == categoryId).ToList();
    public static AIToolDto? GetTool(int id) => _tools.FirstOrDefault(t => t.Id == id);

    public static PagedResult<AIToolDto> SearchTools(AIToolSearchDto search)
    {
        var filtered = _tools.AsEnumerable();
        if (!string.IsNullOrWhiteSpace(search.Query))
        {
            var q = search.Query.ToLowerInvariant();
            filtered = filtered.Where(t =>
                t.Name.ToLowerInvariant().Contains(q) ||
                t.Description.ToLowerInvariant().Contains(q) ||
                (t.Tags?.ToLowerInvariant().Contains(q) ?? false) ||
                t.CategoryName.ToLowerInvariant().Contains(q));
        }
        if (search.CategoryId.HasValue)  filtered = filtered.Where(t => t.CategoryId == search.CategoryId.Value);
        if (search.IsFree.HasValue)      filtered = filtered.Where(t => t.IsFree == search.IsFree.Value);
        if (search.IsFeatured.HasValue)  filtered = filtered.Where(t => t.IsFeatured == search.IsFeatured.Value);

        var all  = filtered.ToList();
        var page = Math.Max(1, search.Page);
        var size = Math.Max(1, search.PageSize);
        return new PagedResult<AIToolDto>
        {
            Items      = all.Skip((page - 1) * size).Take(size).ToList(),
            TotalCount = all.Count,
            Page       = page,
            PageSize   = size,
        };
    }
}
